export const categories = [
  "Headphones",
  "Cameras",
  "Mobiles",
  "Mouse",
  "Speakers",
  "Watches",
];

export const products = [
  // Headphones (ID 1 to 5)
  {
    id: "1",
    name: "Bluetooth Headset Pro",
    description:
      "Experience superior sound quality with these noise-cancelling headphones, perfect for long listening sessions.",
    price: 15,
    offerPrice: 12,
    images: ["product_1.png"],
    categories: ["Headphones"],
    color: "Black",
    date: 1716634345448,
    popular: false,
  },
  {
    id: "2",
    name: "Noise Cancelling Headphones",
    description:
      "A premium wireless headset designed for crystal-clear calls and high-quality audio.",
    price: 22,
    offerPrice: 18,
    images: ["product_2.png"],
    categories: ["Headphones"],
    color: "White",
    date: 1716621345448,
    popular: false,
  },
  {
    id: "3",
    name: "Over-Ear Wireless Headphones",
    description:
      "Comfortable over-ear headphones with advanced sound technology, ideal for music lovers.",
    price: 20,
    offerPrice: 18,
    images: ["product_3.png"],
    categories: ["Headphones"],
    color: "Black",
    date: 1716234545448,
    popular: true,
  },
  {
    id: "4",
    name: "Wireless Noise Cancelling Headphones",
    description:
      "Lightweight and noise-cancelling, designed for immersive listening on the go.",
    price: 80,
    offerPrice: 70,
    images: ["product_4.png"],
    categories: ["Headphones"],
    color: "Red",
    date: 1716621345448,
    popular: false,
  },
  {
    id: "5",
    name: "Gaming Headphones with Mic",
    description:
      "High-quality gaming headphones with a built-in microphone for an immersive gaming experience.",
    price: 40,
    offerPrice: 35,
    images: ["product_5.png"],
    categories: ["Headphones"],
    color: "Black",
    date: 1716622345448,
    popular: false,
  },

  // Cameras (ID 6 to 10)
  {
    id: "6",
    name: "Digital Camera Pro",
    description:
      "Capture stunning photos with this professional-grade digital camera, equipped with advanced features.",
    price: 40,
    offerPrice: 35,
    images: ["product_6.png"],
    categories: ["Cameras"],
    color: "Black",
    date: 1716625345448,
    popular: false,
  },
  {
    id: "7",
    name: "4K DSLR Camera",
    description:
      "A 4K resolution DSLR camera designed for professional photographers and videographers.",
    price: 20,
    offerPrice: 15,
    images: ["product_7.png"],
    categories: ["Cameras"],
    color: "White",
    date: 1716626345448,
    popular: false,
  },
  {
    id: "8",
    name: "Compact Digital Camera",
    description:
      "Compact and lightweight digital camera for everyday use, capturing high-quality images effortlessly.",
    price: 20,
    offerPrice: 18,
    images: ["product_8.png"],
    categories: ["Cameras"],
    color: "Black",
    date: 1716627345448,
    popular: false,
  },
  {
    id: "9",
    name: "Outdoor Action Camera",
    description:
      "Designed for adventurers, this action camera is waterproof and built to capture every moment in high-definition.",
    price: 30,
    offerPrice: 25,
    images: ["product_9.png"],
    categories: ["Cameras"],
    color: "White",
    date: 1716628345448,
    popular: false,
  },
  {
    id: "10",
    name: "Professional Mirrorless Camera",
    description:
      "Mirrorless camera with advanced image stabilization and 4K video recording capability.",
    price: 10,
    offerPrice: 8,
    images: ["product_10.png"],
    categories: ["Cameras"],
    color: "Black",
    date: 1716629345448,
    popular: true,
  },

  // Mobiles (ID 11 to 15)
  {
    id: "11",
    name: "Camera Flash Light",
    description:
      "High-power camera flash light designed to provide excellent lighting in all situations.",
    price: 15,
    offerPrice: 12,
    images: ["product_11.png"],
    categories: ["Mobiles"],
    color: "Black",
    date: 1716632345448,
    popular: true,
  },
  {
    id: "12",
    name: "5G Tecno Mobile",
    description:
      "Durable mobile designed for safety offering convenient storage space.",
    price: 20,
    offerPrice: 18,
    images: ["product_12.png"],
    categories: ["Mobiles"],
    color: "White",
    date: 1716633345448,
    popular: false,
  },
  {
    id: "13",
    name: "Smartphone Camera Lens Kit",
    description:
      "Enhance your smartphone photography with this portable camera lens kit.",
    price: 30,
    offerPrice: 25,
    images: ["product_13.png"],
    categories: ["Mobiles"],
    color: "Black",
    date: 1716634345448,
    popular: false,
  },
  {
    id: "14",
    name: "Mobile Phone 4G",
    description:
      "A high-performance mobile phone featuring a stunning display and powerful battery.",
    price: 10,
    offerPrice: 8,
    images: ["product_14.png"],
    categories: ["Mobiles"],
    color: "White",
    date: 1716635345448,
    popular: false,
  },
  {
    id: "15",
    name: "5G Smartphone",
    description:
      "Experience ultra-fast 5G speeds and high-definition displays with this latest smartphone.",
    price: 30,
    offerPrice: 28,
    images: ["product_15.png"],
    categories: ["Mobiles"],
    color: "Black",
    date: 1716636345448,
    popular: false,
  },

  // Mice (ID 16 to 20)
  {
    id: "16",
    name: "Wireless Gaming Mouse",
    description:
      "Precision wireless mouse designed for gamers with ultra-low latency and ergonomic design.",
    price: 120,
    offerPrice: 100,
    images: ["product_16.png"],
    categories: ["Mouse"],
    color: "Black",
    date: 1716646345448,
    popular: true,
  },
  {
    id: "17",
    name: "Ergonomic Wireless Mouse",
    description:
      "An ergonomic wireless mouse designed for comfort and long hours of usage.",
    price: 90,
    offerPrice: 85,
    images: ["product_17.png"],
    categories: ["Mouse"],
    color: "White",
    date: 1716647345448,
    popular: false,
  },
  {
    id: "18",
    name: "RGB Gaming Mouse",
    description:
      "Customizable RGB gaming mouse with advanced sensor technology and programmable buttons.",
    price: 40,
    offerPrice: 35,
    images: ["product_18.png"],
    categories: ["Mouse"],
    color: "Black",
    date: 1716648345448,
    popular: true,
  },
  {
    id: "19",
    name: "Wireless Mouse with USB Receiver",
    description:
      "Reliable wireless mouse with a USB receiver, ideal for everyday tasks.",
    price: 40,
    offerPrice: 35,
    images: ["product_19.png"],
    categories: ["Mouse"],
    color: "White",
    date: 1716649345448,
    popular: false,
  },
  {
    id: "20",
    name: "Bluetooth Multi-Device Mouse",
    description:
      "Bluetooth mouse that can easily switch between multiple devices, perfect for multitaskers.",
    price: 80,
    offerPrice: 70,
    images: ["product_20.png"],
    categories: ["Mouse"],
    color: "Black",
    date: 1716650345448,
    popular: false,
  },

  // Speakers (ID 21 to 25)
  {
    id: "21",
    name: "Smartwatch Phone",
    description:
      "A smartwatch that connects seamlessly with your phone, offering notifications and more.",
    price: 400,
    offerPrice: 350,
    images: ["product_21.png"],
    categories: ["Speakers"],
    color: "White",
    date: 1716639345448,
    popular: true,
  },
  {
    id: "22",
    name: "Bluetooth Mobile Speaker",
    description:
      "Portable Bluetooth speaker with rich sound quality, perfect for music lovers.",
    price: 50,
    offerPrice: 45,
    images: ["product_22.png"],
    categories: ["Speakers"],
    color: "Black",
    date: 1716640345448,
    popular: false,
  },
  {
    id: "23",
    name: "Portable Wireless Speaker",
    description:
      "Compact and waterproof wireless speaker with deep bass and a long-lasting battery.",
    price: 60,
    offerPrice: 55,
    images: ["product_23.png"],
    categories: ["Speakers"],
    color: "White",
    date: 1716641345448,
    popular: false,
  },
  {
    id: "24",
    name: "Surround Sound Speaker",
    description:
      "Experience immersive surround sound with this speaker designed for home theaters.",
    price: 120,
    offerPrice: 100,
    images: ["product_24.png"],
    categories: ["Speakers"],
    color: "Black",
    date: 1716642345448,
    popular: true,
  },
  {
    id: "25",
    name: "Bluetooth Smart Speaker",
    description:
      "Smart Bluetooth speaker with voice control and advanced sound technology.",
    price: 80,
    offerPrice: 70,
    images: ["product_25.png"],
    categories: ["Speakers"],
    color: "Red",
    date: 1716643345448,
    popular: false,
  },

  // Watches (ID 26 to 30)
  {
    id: "26",
    name: "Fitness Tracker Smartwatch",
    description:
      "Track your fitness goals with this sleek smartwatch, offering heart rate monitoring and activity tracking.",
    price: 70,
    offerPrice: 60,
    images: ["product_26.png"],
    categories: ["Watches"],
    color: "Black",
    date: 1716644345448,
    popular: false,
  },
  {
    id: "27",
    name: "Smart Fitness Watch",
    description:
      "Stylish fitness watch with built-in GPS and tracking for every workout.",
    price: 50,
    offerPrice: 40,
    images: ["product_27.png"],
    categories: ["Watches"],
    color: "White",
    date: 1716645345448,
    popular: false,
  },
  {
    id: "28",
    name: "Smartwatch with Heart Rate Monitor",
    description:
      "All-in-one smartwatch with heart rate tracking, sleep analysis, and activity monitoring.",
    price: 120,
    offerPrice: 100,
    images: ["product_28.png"],
    categories: ["Watches"],
    color: "Black",
    date: 1716646345448,
    popular: true,
  },
  {
    id: "29",
    name: "Luxury Smartwatch",
    description:
      "Premium smartwatch with luxury finish, featuring advanced health tracking and notifications.",
    price: 200,
    offerPrice: 170,
    images: ["product_29.png"],
    categories: ["Watches"],
    color: "Gold",
    date: 1716647345448,
    popular: true,
  },
  {
    id: "30",
    name: "Waterproof Smartwatch",
    description:
      "Perfect for swimmers, this waterproof smartwatch offers fitness tracking, calls, and notifications.",
    price: 90,
    offerPrice: 80,
    images: ["product_30.png"],
    categories: ["Watches"],
    color: "Blue",
    date: 1716648345448,
    popular: false,
  },
];
